# Generated by Django 3.2.8 on 2021-11-09 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_auto_20211108_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='due_date',
        ),
    ]
